backend:
  name: github
  repo: balint-miklos/ski-results
  branch: main
  # This line tells Decap CMS to use the modern PKCE auth flow, 
  # which works better with GitHub Pages and custom domains.
  auth_type: pkce

# Optional media folders
media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "settings"
    label: "Settings"
    files:
      - name: "crawl_targets_test"
        label: "Test Crawl Targets"
        file: "data/crawl_targets_test.json"
        fields:
          - name: targets
            label: "Crawl Targets"
            widget: list
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
              - label: "Status"
                name: "status"
                widget: "select"
                options: ["queued", "crawling", "processed", "failed"]
              - label: "Event"
                name: "event"
                widget: "object"
                fields:
                  - { label: "Start Date", name: "startDate", widget: "datetime", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", timeFormat: false }
                  - { label: "End Date", name: "endDate", widget: "datetime", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", timeFormat: false }
              - label: "Crawl Policy"
                name: "crawlPolicy"
                widget: "object"
                fields:
                  - { label: "Valid From", name: "validFrom", widget: "datetime" }
                  - { label: "Valid Until", name: "validUntil", widget: "datetime" }
              - label: "Tracking"
                name: "tracking"
                widget: "object"
                fields:
                  - { label: "Created At", name: "createdAt", widget: "datetime" }
                  - { label: "Updated At", name: "updatedAt", widget: "datetime" }
                  - { label: "Attempt Count", name: "attemptCount", widget: "number", value_type: "int" }
                  - { label: "Last Attempt At", name: "lastAttemptAt", widget: "datetime", required: false }
                  - { label: "Succeeded At", name: "succeededAt", widget: "datetime", required: false }